name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
  # run once every month
    - cron:  '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate My PRs List 👀
      uses: Bhupesh-V/moc@main
      with:
        username: "${{ github.actor }}"
        filename: "README.md"
#     - name: Update README
#       run: |-
#         python3 my-prs.py Bhupesh-V
#     - name: Push new README.md
#       uses: mikeal/publish-to-github-action@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
