name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '12 2 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update README
      run: |-
        python my-prs.py Bhupesh-V
    - name: Push new README.md
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
